#!/usr/bin/env bash



# Append a header to a file if it doesn't exist
function add_header_to_file () {
    if is_empty "${1}"; then
        alert_die "File must be given as first parameter to 'add_header_to_file'."
    fi
    if is_not_file "${1}"; then
        alert_die "File given as first parameter to 'add_header_to_file' must exists and be a file."
    fi
    if is_empty "${2}"; then
        alert_die "Header string must be given as second parameter to 'add_header_to_file'."
    fi

    if ! grep -q ${2} ${1}; then
        alert_info "Writing header line"
        echo -e "\n\n" >> ${1}
        echo "${2}" >> ${1}
    fi
}


# Append an entry to a file if it doesn't exist
function add_entry_to_file () {
    if type_not_exists "pcregrep"; then
        seek_confirmation "You need 'pcregrep', do you want to install it?"
        if is_not_confirmed; then
            alert_die "Can't continue without 'pcregrep'."
        fi
        package_install "pcregrep"
    fi
    if is_empty "${1}"; then
        alert_die "File must be given as first parameter to 'add_entry_to_file'."
    fi
    if is_not_file "${1}"; then
        alert_die "File given as first parameter to 'add_entry_to_file' must exists and be a file."
    fi
    if is_empty "${2}"; then
        alert_die "Entry string must be given as second parameter to 'add_entry_to_file'."
    fi

    if pcregrep -M -q "${2}" ${1}; then
        alert_notice "Entry already added"
    else
        echo -e "\n" >> ${1}
        echo "${2}" >> ${1}
        alert_success "Added entry to '${1}': \n${2}"
    fi
}


# Remove all autogenerated entries from a file
function clean_autogenerated_from_file () {
    if is_empty "${1}"; then
        alert_die "File must be given as first parameter to 'clean_autogenerated_from_file'."
    fi
    if is_not_file "${1}"; then
        alert_die "File given as first parameter to 'clean_autogenerated_from_file' must exists and be a file."
    fi
    if is_empty "${2}"; then
        alert_die "Header string must be given as second parameter to 'clean_autogenerated_from_file'."
    fi

    # Get everything before header and discard everything after
    userPartOfFile=$(cat "${1}" | awk "/${2}/ {exit} {print}")

    # Write the file with only the user part
    echo "${userPartOfFile}" > ${1}

    alert_success "Removed all autogenerated entries from '${1}'."
}
